(add-to-list 'load-path "/home/bloat/dev/src/lisp/elisp/glulx")
(add-to-list 'load-path "/home/bloat/dev/src/lisp/elisp/glk")

(require 'glx-exec)
(require 'glx-glk)
(require 'glx-glulx)
(require 'glx-instructions)
(require 'glx-load)
(require 'glx-stack)
(require 'glx-string)
(require 'glx-value)
(require 'glx-compile)

(require 'glk-base)
(require 'glk-customize)
(require 'glk)
(require 'glk-encoding)
(require 'glk-event)
(require 'glk-file)
(require 'glk-function-dispatch)
(require 'glk-opaque)
(require 'glk-stream)
(require 'glk-window)

(load "glx-value-spec.el")
(load "glx-glulx-spec.el")
(load "glx-stack-spec.el")
(load "glx-string-spec.el")
(load "glx-exec-spec.el")
(load "glx-load-spec.el")
(load "glx-instructions-spec.el")
(load "glx-glk-spec.el")
(load "glx-compile-spec.el")

(load "window-spec")
(load "function-dispatch-spec")
(load "stream-spec")
(load "event-spec")
(load "mode-spec")
(load "event-spec")
(load "encoding-spec")
(load "file-spec")
(load "opaque-spec")
